### PR TITLE
Ported to boto3

### PR DESCRIPTION
**Pull request by romanopritz**
Hi! Thanks for this module, came in handy. Had to rewrite it for boto3 though.

### CODE REVIEW

**Comment by ozbillwang** [comment]
Could we create a new file then we can support both boto2 and boto3?

My current environment is still running with boto2.

**Comment by romanopritz** [comment]
Yes, I guess so. Feel free to add it as a new file.

**Comment by ozbillwang** [comment]
The PR looks fine to me. 

Could you rename the file, such as `aws_tags_3.py`? Otherwise I can't merge it. 

Thanks.

**Comment by romanopritz** [comment]
Renamed to aws_tags3.py which means a new name for Ansible module. Not sure how to handle this.

**Comment by ozbillwang** [comment]
Good question. Not sure how ansible itself handles both boto2 and boto3 scripts at same time.

**Pull request merged**
